services:
  mongodb:
    image: mongo:4.4
    container_name: songs_mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - songs_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/songs --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  songs_api:
    build: .
    container_name: songs_api
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017/songs
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - songs_network
    command: >
      sh -c "python scripts/import_songs.py --file songs.json --drop &&
             python scripts/run.py"

networks:
  songs_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
